<robot name="mycar" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- 雷达部件 -->
    <!-- 参数 -->
    <!-- 
        1.支架
            支架尺寸：半径  高度
            关节偏移量：x y z
        2.雷达
            雷达尺寸：半径  高度
            关节偏移量:x y z
     -->
     <xacro:property name="suport_radius" value="0.01" />
     <xacro:property name="suport_length" value="0.15" />
     <xacro:property name="laser_radius" value="0.03" />
     <xacro:property name="laser_length" value="0.05" />

     <xacro:property name="joint_suport_x" value="0" />
     <xacro:property name="joint_suport_y" value="0" />
     <xacro:property name="joint_suport_z" value="${base_length / 2 + suport_length / 2}" />
     <xacro:property name="joint_laser_x" value="0" />
     <xacro:property name="joint_laser_y" value="0" />
     <xacro:property name="joint_laser_z" value="${suport_length/2+laser_length/2}" />


    <!-- 1.支架的设计-->
    <link name="suport">
        <visual>
            <geometry>
                <cylinder radius="${suport_radius}" length="${suport_length}" />
            </geometry>

            <origin xyz="0 0 0" rpy="0 0 0" />
            
            <material name="suportlink_color">
                <color rgba="0.8 0.5 0 0.5" />
            </material>    
        </visual>
    </link>
    <joint name="suport2base" type="fixed">
        <parent link="base_link" />
        <child link="suport" />
        <!-- 关节z上的设置 = 车体高度/2 +离地间距 -->
        <origin xyz="0 0 ${joint_suport_z}" rpy="0 0 0" />
    </joint>
    <!-- 2.雷达 -->
    <link name="laser">
        <visual>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}" />
            </geometry>

            <origin xyz="0 0 0" rpy="0 0 0" />
            
            <material name="laserlink_color">
                <color rgba="0 0 0 0.5" />
            </material>    
        </visual>
    </link>
    <joint name="laser2suport" type="fixed">
        <parent link="suport" />
        <child link="laser" />
        <!-- 关节z上的设置 = 车体高度/2 +离地间距 -->
        <origin xyz="${joint_laser_x} ${joint_laser_y} ${joint_laser_z}" rpy="0 0 0" />
    </joint>

</robot>